// AUTO-GENERATED by scripts/gen-seed-data.mjs from docs/label_frequencies.json
// Do not edit by hand — re-run the generator instead.

// [code, name_th, name_en, name_mm, name_zh, sort_order]
const LABEL_FREQUENCIES: [string, string, string, string, string, number][] = [["01","วันละ 1 ครั้ง","Once daily","တစ်နေ့ ၁ ကြိမ်","每日1次",0],["02","วันละ 2 ครั้ง","Twice daily","တစ်နေ့ ၂ ကြိမ်","每日2次",1],["03","วันละ 3 ครั้ง","Three times daily","တစ်နေ့ ၃ ကြိမ်","每日3次",2],["04","วันละ 4 ครั้ง","Four times daily","တစ်နေ့ ၄ ကြိမ်","每日4次",3],["05","วันละ 5 ครั้ง","Five times daily","တစ်နေ့ ၅ ကြိမ်","每日5次",4],["06","สัปดาห์ละ 1 ครั้ง","Once weekly","တစ်ပတ် ၁ ကြိမ်","每周1次",5],["07","เดือนละ 1 ครั้ง","Once monthly","တစ်လ ၁ ကြိမ်","每月1次",6],["08","วันละ 2-3 ครั้ง","2-3 times daily","တစ်နေ့ ၂ ကြိမ်မှ ๓ ကြိမ်အထိ","每日2-3次",7],["09","วันละ 3-4 ครั้ง","3-4 times daily","တစ်နေ့ ๓ ကြိမ်မှ ๔ ကြိမ်อထိ","每日3-4次",8]]

export default LABEL_FREQUENCIES
