// AUTO-GENERATED by scripts/gen-seed-data.mjs from docs/label_meal_relations.json
// Do not edit by hand — re-run the generator instead.

// [code, name_th, name_en, name_mm, name_zh, sort_order]
const LABEL_MEAL_RELATIONS: [string, string, string, string, string, number][] = [["01","ก่อนอาหาร","before meal","အစာမစားမီ","餐前",0],["02","หลังอาหาร","after meal","အစာစားပြီး","餐后",1],["03","พร้อมอาหาร","with meal","အစာနှင့်အတူ","随餐服用",2],["04","หลังอาหารทันที","right after meal","အစာစားပြီးချက်ချင်း","饭后立即服用",3],["05","ก่อนอาหาร 30 นาที","30 mins before meal","အစာမစားမီ မိနစ် ၃၀","餐前30分钟",4],["06","หลังอาหาร 30 นาที","30 mins after meal","အစာစားပြီး မိနစ် ၃၀","餐后30分钟",5],["07","ขณะท้องว่าง","on empty stomach","ဗိုက်ဟောင်းနေချိန်တွင်","空腹",6],["08","ไม่ต้องคำนึงถึงมื้ออาหาร","with or without food","အစားအစာနှင့်မဆိုင်ဘဲ","饭前或饭后服用均可",7],["09","ก่อนอาหาร 1 ชั่วโมง","1 hour before meal","အစာမစားမီ ၁ နာรီ","餐前1小时",8],["10","หลังอาหาร 1 ชั่วโมง","1 hour after meal","အစာစားပြီး ၁ နာရီ","餐后1小时",9],["11","ก่อนอาหาร 2 ชั่วโมง","2 hours before meal","အစာမစားမီ ၂ နာရီ","餐前2小时",10],["12","หลังอาหาร 2 ชั่วโมง","2 hours after meal","အစာစားပြီး ၂ နาရี","餐后2小时",11],["13","ทานทันทีเมื่อเริ่มมีอาการ","take right when symptom occurs","ရောဂါလက္ခဏาစပြလျှင်ချက်ချင်းသောက်ပါ","症状出现时立即服用",12]]

export default LABEL_MEAL_RELATIONS
