# Regenerable transform: docs/Item.xlsx -> electron/db/seed-data/products.ts
#
# Source of truth is the raw Hygeia export docs/Item.xlsx (sheet "Item").
# Output is a TS module bundled into main.js by rollup, so the data travels
# with the app and the runtime never reads the spreadsheet.
#
# Per-table convention: one gen script per seeded table, self-contained.
# Replaces the old gen-products.mjs (which read a lossy intermediate
# docs/Item.json) — the xlsx is now read directly so nothing is lost.
#
# Run:  python scripts/gen-products.py      (needs:  pip install openpyxl)

import json
import re
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "Item.xlsx"
OUT = ROOT / "electron" / "db" / "seed-data" / "products.ts"


def s(v):
    """-> string. None -> ''. Integer-valued floats lose the '.0' so numeric
    barcodes don't come out as '8.85e12' / '12345.0'."""
    if v is None:
        return ""
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


def n(v):
    """-> number. Blank / non-numeric -> 0 (same as the old `Number(v)||0`)."""
    try:
        return v if isinstance(v, (int, float)) and not isinstance(v, bool) else float(v)
    except (TypeError, ValueError):
        return 0


def b(v):
    """-> 0/1. Handles openpyxl booleans, 0/1, and '0'/'1'/'' strings."""
    if isinstance(v, str):
        return 1 if v.strip() not in ("", "0", "False", "false") else 0
    return 1 if v else 0


# Drop unusable junk products: names that are blank, numeric-only, code/barcode
# dumps, or "N/A"/"NA"/"xx" placeholders. Real short codes (D2, D5, TDS, PDL)
# have letters and are intentionally kept. (Same policy as the old generator.)
def is_junk_name(name):
    t = s(name).strip()
    if not t:
        return True
    if re.fullmatch(r"[0-9.\-/ ]+", t):  # numeric / symbol only
        return True
    if re.fullmatch(r"[0-9*]+", t):  # barcode-as-name
        return True
    if re.fullmatch(r"(n/a|na|xx)", t, re.I):  # placeholders
        return True
    return False


def cost_price(row, idx):
    """round(MovAvgPrice, 4); fall back to UnitPrice when MovAvg is 0/blank."""
    mv = n(row[idx["MovAvgPrice"]])
    up = n(row[idx["UnitPrice"]])
    return round(mv, 4) if mv else up


wb = openpyxl.load_workbook(SRC, read_only=True, data_only=True)
ws = wb["Item"]
it = ws.iter_rows(values_only=True)
header = list(next(it))
idx = {h: i for i, h in enumerate(header)}
rows = [list(r) for r in it]

named = [r for r in rows if not is_junk_name(r[idx["Name"]])]
dropped_junk = len(rows) - len(named)
# Drop disabled (ปิดใช้งาน) products entirely — they are not seeded.
kept = [r for r in named if not b(r[idx["IsDisabled"]])]
dropped_disabled = len(named) - len(kept)
dropped = len(rows) - len(kept)

# `Code` (IT-0000001…) is intentionally NOT emitted — the seed assigns running
# P#### codes (same sequence as products:create) so seeded + user-created
# products share one code space.
tuples = []
for r in kept:
    tuples.append([
        s(r[idx["Name"]]), s(r[idx["NameForPrint"]]), s(r[idx["OtherName"]]),
        s(r[idx["BarCode"]]), s(r[idx["BarCode2"]]),
        s(r[idx["BarCode3"]]), s(r[idx["BarCode4"]]),
        s(r[idx["SaleUnitName"]]),
        cost_price(r, idx), n(r[idx["SalePrice"]]),
        n(r[idx["Wholesale1"]]), n(r[idx["Wholesale2"]]),
        b(r[idx["IsDisabled"]]), b(r[idx["IsHidden"]]),
        b(r[idx["IsStockItem"]]), b(r[idx["IsTax"]]),
        1 if r[idx["DrugACPCKey"]] is not None else 0,
        s(r[idx["TMTID"]]), s(r[idx["Note"]]),
        n(r[idx["ReorderPoint"]]), n(r[idx["QtyReq"]]),
    ])

T = ("[string, string, string, string, string, string, string, string, "
     "number, number, number, number, number, number, number, number, "
     "number, string, string, number, number]")

body = (
    "// AUTO-GENERATED by scripts/gen-products.py from docs/Item.xlsx\n"
    "// Do not edit by hand — re-run the generator instead.\n\n"
    "// Tuple shape (no code — seed assigns running P#### codes):\n"
    "//   [trade_name, name_for_print, search_keywords,\n"
    "//    barcode, barcode2, barcode3, barcode4,\n"
    "//    unit_name, cost_price, price_retail, price_wholesale1, price_wholesale2,\n"
    "//    is_disabled, is_hidden, is_stock_item, has_vat, is_drug,\n"
    "//    tmt_id, note, reorder_point, safety_stock]\n"
    f"const PRODUCTS: {T}[] = "
    + json.dumps(tuples, ensure_ascii=False, separators=(",", ":"))
    + "\n\nexport default PRODUCTS\n"
)

OUT.write_text(body, encoding="utf-8")
print(
    f"products.ts: {len(tuples)} rows "
    f"(dropped {dropped_junk} junk-named, {dropped_disabled} disabled; "
    f"{dropped} total)"
)
